esolving_eschool_userB_Student_delete:
    pattern: /{studentId}/delete
    defaults: { _controller: EsolvingEschoolUserBundle:Student:delete }    

esolving_eschool_userB_Student_show:
    pattern: /{studentId}/show
    defaults: { _controller: EsolvingEschoolUserBundle:Student:show }
    
esolving_eschool_userB_Student_edit:
    pattern: /{studentId}/edit
    defaults: { _controller: EsolvingEschoolUserBundle:Student:edit }    
    
esolving_eschool_userB_Student_list:
    pattern: /list
    defaults: { _controller: EsolvingEschoolUserBundle:Student:list }
    
esolving_eschool_userB_Student_register:
    pattern: /register
    defaults: { _controller: EsolvingEschoolUserBundle:Student:register }