esolving_eschool_userB_Teacher_delete:
    pattern: /{teacherId}/delete
    defaults: { _controller: EsolvingEschoolUserBundle:Teacher:delete }    

esolving_eschool_userB_Teacher_edit:
    pattern: /{teacherId}/edit
    defaults: { _controller: EsolvingEschoolUserBundle:Teacher:edit }    

esolving_eschool_userB_Teacher_show:
    pattern: /{teacherId}/show
    defaults: { _controller: EsolvingEschoolUserBundle:Teacher:show }        
    
esolving_eschool_userB_Teacher_list:
    pattern: /list
    defaults: { _controller: EsolvingEschoolUserBundle:Teacher:list }    
    
esolving_eschool_userB_Teacher_register:
    pattern: /register
    defaults: { _controller: EsolvingEschoolUserBundle:Teacher:register }